// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI78cjVwHqAs_gYf43FgpbnwIAmr2XI3I',
    appId: '1:977175503820:web:e457c3f426cc6ea0eb7369',
    messagingSenderId: '977175503820',
    projectId: 'market-bridge-6ef72',
    authDomain: 'market-bridge-6ef72.firebaseapp.com',
    storageBucket: 'market-bridge-6ef72.firebasestorage.app',
    measurementId: 'G-TGCEZG9LCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOKxPWoUWGDjOQA7S2443rtz3ST62EQM',
    appId: '1:977175503820:android:4ff43c58d56bf407eb7369',
    messagingSenderId: '977175503820',
    projectId: 'market-bridge-6ef72',
    storageBucket: 'market-bridge-6ef72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKTF2XJtck1Yq10GpwL2qR1A74cQJr9Z4',
    appId: '1:977175503820:ios:9c4f050d9711c06eeb7369',
    messagingSenderId: '977175503820',
    projectId: 'market-bridge-6ef72',
    storageBucket: 'market-bridge-6ef72.firebasestorage.app',
    iosBundleId: 'com.example.marketBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKTF2XJtck1Yq10GpwL2qR1A74cQJr9Z4',
    appId: '1:977175503820:ios:9c4f050d9711c06eeb7369',
    messagingSenderId: '977175503820',
    projectId: 'market-bridge-6ef72',
    storageBucket: 'market-bridge-6ef72.firebasestorage.app',
    iosBundleId: 'com.example.marketBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI78cjVwHqAs_gYf43FgpbnwIAmr2XI3I',
    appId: '1:977175503820:web:ce345754a5aaf92eeb7369',
    messagingSenderId: '977175503820',
    projectId: 'market-bridge-6ef72',
    authDomain: 'market-bridge-6ef72.firebaseapp.com',
    storageBucket: 'market-bridge-6ef72.firebasestorage.app',
    measurementId: 'G-3FGXZCDFXH',
  );

}